import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM="xterm-256color"

[window.class]
instance = "Alacritty"
general = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 5

[window]
opacity=0.9
blur=true

[scrolling]
history = 20000
multiplier = 5

[font]
size = 11 

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"


