import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 13

[env]
TERM="xterm-256color"

[window]
opacity=0.7
blur=false
decorations="None"
startup_mode="Maximized"

[window.class]
instance = "Alacritty"
general = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 8
y = 10

[scrolling]
history = 20000
multiplier = 5

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"
